package enumeracije;

public enum Sluzba {
	SLUZBA_OPSTE_MEDICINE, ZDRAVSTVENA_ZASTITA_DJECE, STOMATOLOSKA_SLUZBA, ZDRAVSTVENA_ZASTITA_RADINKA, SLUZBA_ZA_PRAVNE_I_EKONOMSKE_POSLOVE, SLUZBA_ZA_TEHNICKE_POSLOVE
}
